NAME = ScavTrap
SRC = ScavTrap.cpp main.cpp ClapTrap.cpp
FLAG = -Wall -Wextra -Werror -std=c++98

$(NAME):
	c++ $(FLAG) $(SRC) -o $(NAME)

clean:
		rm -f $(NAME)

fclean: clean

all: $(NAME)

re: fclean all