NAME = Bureaucrat
SRC = main.cpp Bureaucrat.cpp
FLAG = -Wall -Wextra -Werror -std=c++98

$(NAME):
	g++ $(FLAG) $(SRC) -o $(NAME)

all: $(NAME)

clean:
	rm -f all

fclean: clean

re:
	fclean all