NAME = Form
SRC = main.cpp Bureaucrat.cpp Form.cpp
FLAG = -Wall -Wextra -Werror -std=c++98

$(NAME):
	g++ $(FLAG) $(SRC) -o $(NAME)

all: $(NAME)

clean:
	rm -f $(NAME)

fclean: clean

re:
	fclean all